var pets = [
  {
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    sex: "Male",
    color: "Tri-color (Black, Brown, White)",
    spayed: "Yes",
    age: "5 Years",
    id: "34621",
    chip: "982000364789210",
    about:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Luna",
    type: "Cat",
    breed: "Maine Coon",
    sex: "Female",
    color: "Grey with white markings",
    spayed: "Yes",
    age: "3 Years",
    id: "57281",
    chip: "981120019776432",
    about:
      "Luna is a majestic Maine Coon with a fluffy grey coat and striking white markings. She was found as a stray and has since become a gentle and affectionate companion. Luna enjoys perching on windowsills, watching birds, and being the center of attention. She's a bit shy at first but warms up quickly, especially if you have treats! Luna would thrive in a calm environment where she can relax and be pampered like the queen she is.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Sandy",
    type: "Dog",
    breed: "Golden Retriever",
    sex: "Female",
    color: "Golden",
    spayed: "Yes",
    age: "7 Years",
    id: "41382",
    chip: "985112004567890",
    about:
      "Sandy is a heartwarming Golden Retriever with a golden coat as bright as her personality. Rescued from a neglectful situation, she has shown incredible resilience and love for life. Sandy is great with children and other pets, making her an ideal family dog. She enjoys outdoor adventures, especially swimming and fetching. Sandy is looking for a forever home where she can spread her joy and love.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Oliver",
    type: "Cat",
    breed: "Siamese",
    sex: "Male",
    color: "Seal Point",
    spayed: "Yes",
    age: "2 Years",
    id: "62894",
    chip: "981120025678902",
    about:
      "Oliver is a sleek Siamese cat with striking blue eyes and a seal point coat. Found wandering in a neighborhood, he's adapted well to shelter life but is eager for a permanent home. Oliver is vocal, expressing his thoughts freely, and enjoys interactive playtime. He's affectionate and loves to be close to his human companions, often following them around the house. Oliver would do best in a home where he can receive plenty of attention and love.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Max",
    type: "Dog",
    breed: "Labrador Retriever",
    sex: "Male",
    color: "Chocolate",
    spayed: "Yes",
    age: "4 Years",
    id: "47920",
    chip: "985120031478902",
    about:
      "Max is a charming Chocolate Labrador with a love for life and a tail that never stops wagging. Rescued from an overcrowded shelter, Max has shown immense gratitude and loyalty to his caregivers. He is full of energy and would thrive in a home with a backyard or regular access to outdoor activities. Max is great with children and other dogs, and he's always up for a game of fetch or a leisurely walk. His ideal home would be with an active family who can match his energy and zest for life.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Daisy",
    type: "Cat",
    breed: "Persian",
    sex: "Female",
    color: "White",
    spayed: "Yes",
    age: "6 Years",
    id: "58329",
    chip: "981120036712345",
    about:
      "Daisy is a stunning white Persian cat with a luxurious coat and gentle demeanor. She was surrendered by an owner who could no longer care for her. Daisy is a bit of a diva and loves being the center of attention. She enjoys being groomed and will happily sit in your lap for hours. She's not fond of loud noises or fast movements, so a quiet and calm household would be ideal. Daisy is looking for a loving home where she can be pampered and adored.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Charlie",
    type: "Dog",
    breed: "Dachshund",
    sex: "Male",
    color: "Dapple",
    spayed: "Yes",
    age: "3 Years",
    id: "49583",
    chip: "982000367829101",
    about:
      "Charlie is a spirited Dapple Dachshund with a playful personality. He was found as a stray and has since shown an incredible zest for life. Charlie loves exploring, whether it's a new trail or the corners of his home. He's a bit mischievous and enjoys hiding his toys. Charlie would do well in a home with an individual or family who enjoys fun and adventure. He's small but has a big heart and a lot of love to give.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "George",
    type: "Cat",
    breed: "British Shorthair",
    sex: "Male",
    color: "Blue (Gray)",
    spayed: "Yes",
    age: "4 Years",
    id: "61029",
    chip: "985112007651234",
    about:
      "George is a robust British Shorthair with a striking blue-gray coat and a calm, dignified demeanor. Rescued from a busy city environment, he's adapted well to a quieter life. George enjoys leisurely days, lounging in sunny spots, and watching the world go by. He's not overly demanding for attention but appreciates a good chin scratch and will purr loudly in response. George is a bit reserved at first but becomes a loyal companion once he feels comfortable. He would be perfect for someone seeking a low-maintenance, independent cat.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Bella",
    type: "Dog",
    breed: "Boxer",
    sex: "Female",
    color: "Fawn with white markings",
    spayed: "Yes",
    age: "1 Year",
    id: "50824",
    chip: "982000360234567",
    about:
      "Bella is a spirited Boxer with a fawn coat and charming white markings. She was rescued from a neglectful situation and has shown immense love and gratitude to her caregivers. Bella is energetic and playful, enjoying activities like running and playing fetch. She's great with older children and would thrive in a home where she can be active and engaged. Bella has a big personality and would be a fantastic companion for someone who loves adventure and fun.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Sophie",
    type: "Cat",
    breed: "Ragdoll",
    sex: "Female",
    color: "Seal point with blue eyes",
    spayed: "Yes",
    age: "1 Year",
    id: "63845",
    chip: "985112008765432",
    about:
      "Sophie is a young Ragdoll cat with a soft seal point coat and mesmerizing blue eyes. She was found as a kitten and raised in a foster home. Sophie is incredibly affectionate, often seeking out laps to curl up in. She's playful and enjoys interactive toys, but she's also content to relax and watch the world go by. Sophie gets along well with other pets and would be an excellent addition to a loving family or individual looking for a gentle and loving companion.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },

  {
    name: "Milo",
    type: "Dog",
    breed: "Shih Tzu",
    sex: "Male",
    color: "White with brown markings",
    spayed: "Yes",
    age: "2 Years",
    id: "72513",
    chip: "982000364712345",
    about:
      "Milo is a charming Shih Tzu with a fluffy white coat and adorable brown markings. He has a gentle and affectionate demeanor, always eager to cuddle up with his human companions. Milo enjoys short walks and playing with his favorite toys, especially plushies. He's great with children and other pets, making him a delightful addition to any family. Milo is looking for a loving home where he can receive plenty of attention and affection.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Mittens",
    type: "Cat",
    breed: "Domestic Shorthair",
    sex: "Female",
    color: "Calico",
    spayed: "Yes",
    age: "3 Years",
    id: "83476",
    chip: "981120036743210",
    about:
      "Mittens is a beautiful Calico cat with a playful and curious personality. She enjoys exploring her surroundings and investigating every nook and cranny of her home. Mittens is affectionate and enjoys being petted, but she also has a independent streak and appreciates her alone time. She's great with children and other cats, making her an ideal companion for a loving family. Mittens is looking for a forever home where she can continue to thrive and bring joy to her new family.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Rocky",
    type: "Dog",
    breed: "German Shepherd",
    sex: "Male",
    color: "Black and Tan",
    spayed: "Yes",
    age: "6 Years",
    id: "93625",
    chip: "982000364721987",
    about:
      "Rocky is a loyal German Shepherd with a striking black and tan coat and intelligent eyes. He has a calm and confident demeanor, always ready to protect and serve his family. Rocky is well-trained and knows basic commands, making him an obedient companion. He enjoys long walks, outdoor adventures, and playing fetch. Rocky is great with older children and adults but can be cautious around strangers. He's looking for a loving and experienced owner who can provide him with structure, exercise, and plenty of love.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Whiskers",
    type: "Cat",
    breed: "Scottish Fold",
    sex: "Male",
    color: "Tabby",
    spayed: "Yes",
    age: "4 Years",
    id: "10472",
    chip: "981120036712389",
    about:
      "Whiskers is a handsome Scottish Fold with a charming tabby coat and adorable folded ears. He has a laid-back and affectionate personality, often seeking out laps to curl up in. Whiskers enjoys lounging in sunny spots and watching birds through the window. He's great with children and other cats, making him an ideal companion for a loving family. Whiskers is looking for a forever home where he can receive plenty of attention and love.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Rosie",
    type: "Dog",
    breed: "Cocker Spaniel",
    sex: "Female",
    color: "Golden",
    spayed: "Yes",
    age: "5 Years",
    id: "11657",
    chip: "982000364782345",
    about:
      "Rosie is a sweet Cocker Spaniel with a golden coat and a wagging tail that never stops. She has a gentle and affectionate demeanor, always eager to shower her human companions with love and kisses. Rosie enjoys leisurely walks, playing fetch, and snuggling up on the couch. She's great with children and other dogs, making her a wonderful addition to any family. Rosie is looking for a forever home where she can be cherished and adored.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Felix",
    type: "Cat",
    breed: "Tabby",
    sex: "Male",
    color: "Orange",
    spayed: "Yes",
    age: "2 Years",
    id: "12893",
    chip: "981120036712390",
    about:
      "Felix is a playful Tabby cat with a vibrant orange coat and a mischievous twinkle in his eyes. He loves to explore his surroundings and is always finding new places to hide and play. Felix is affectionate and enjoys being petted, especially behind his ears. He's great with children and other cats, making him an ideal companion for a loving family. Felix is looking for a forever home where he can bring joy and laughter to his new family.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Cooper",
    type: "Dog",
    breed: "Australian Shepherd",
    sex: "Male",
    color: "Red Merle",
    spayed: "Yes",
    age: "3 Years",
    id: "13579",
    chip: "982000364785321",
    about:
      "Cooper is a vibrant Australian Shepherd with a stunning red merle coat and bright, intelligent eyes. He has a playful and energetic personality, always ready for a game of fetch or a long hike in the great outdoors. Cooper is highly intelligent and eager to please, making him a joy to train. He's great with children and other dogs, but he can be shy around new people. Cooper is looking for an active and loving home where he can thrive and continue to explore the world.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Misty",
    type: "Cat",
    breed: "Persian",
    sex: "Female",
    color: "Silver",
    spayed: "Yes",
    age: "4 Years",
    id: "14208",
    chip: "981120036712391",
    about:
      "Misty is a beautiful Persian cat with a luxurious silver coat and stunning green eyes. She has a calm and gentle demeanor, always exuding an air of elegance and grace. Misty enjoys lounging in sunny spots and being pampered with gentle strokes. She's great with older children and adults, but she prefers a quieter environment without too much commotion. Misty is looking for a loving and attentive home where she can be treated like the queen she truly is.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Oscar",
    type: "Dog",
    breed: "Pug",
    sex: "Male",
    color: "Fawn",
    spayed: "Yes",
    age: "2 Years",
    id: "15734",
    chip: "982000364782345",
    about:
      "Oscar is an adorable Pug with a wrinkled face and a playful personality. He loves nothing more than to snuggle up with his human companions and receive belly rubs. Oscar enjoys short walks and playing with his favorite toys, especially ones that squeak. He's great with children and other pets, making him a delightful addition to any family. Oscar is looking for a forever home where he can be showered with love and attention.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Lily",
    type: "Cat",
    breed: "Russian Blue",
    sex: "Female",
    color: "Blue",
    spayed: "Yes",
    age: "3 Years",
    id: "16952",
    chip: "981120036712392",
    about:
      "Lily is a graceful Russian Blue with a sleek blue coat and piercing green eyes. She has a reserved yet affectionate demeanor, often curling up in her favorite spot by the window to watch the world go by. Lily enjoys gentle petting and quiet companionship, but she can be playful when the mood strikes. She's great with older children and adults, preferring a calm and tranquil environment. Lily is looking for a loving home where she can be cherished and appreciated.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },

  {
    name: "Teddy",
    type: "Dog",
    breed: "Cavalier King Charles Spaniel",
    sex: "Male",
    color: "Blenheim",
    spayed: "Yes",
    age: "5 Years",
    id: "17543",
    chip: "982000364782367",
    about:
      "Teddy is a lovable Cavalier King Charles Spaniel with a gorgeous Blenheim coat and expressive eyes. He has a gentle and affectionate personality, always eager to snuggle up with his human companions. Teddy enjoys leisurely walks, exploring new scents, and playing with his favorite toys. He's great with children and other dogs, making him a wonderful addition to any family. Teddy is looking for a forever home where he can be showered with love and attention.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Jack",
    type: "Cat",
    breed: "Maine Coon",
    sex: "Male",
    color: "Brown Tabby",
    spayed: "Yes",
    age: "4 Years",
    id: "18329",
    chip: "981120036712393",
    about:
      "Jack is a magnificent Maine Coon with a stunning brown tabby coat and a majestic mane. He has a laid-back and affectionate personality, often seeking out laps to curl up in. Milo enjoys lounging in sunny spots, bird watching, and playing with feather toys. He's great with children and other pets, making him an ideal companion for a loving family. Milo is looking for a forever home where he can be cherished and appreciated for the regal cat that he is.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Bailey",
    type: "Dog",
    breed: "Border Collie",
    sex: "Female",
    color: "Black and White",
    spayed: "Yes",
    age: "3 Years",
    id: "19658",
    chip: "982000364782368",
    about:
      "Bailey is an energetic Border Collie with a striking black and white coat and intelligent eyes. She has a playful and adventurous personality, always ready for a game of frisbee or a long hike in the countryside. Bailey is highly intelligent and thrives on mental stimulation and learning new tricks. She's great with children and other dogs, but her herding instincts can be strong, so she needs an experienced owner who can provide her with plenty of exercise and training. Bailey is looking for an active and loving home where she can fulfill her potential as a working dog and beloved companion.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Cleo",
    type: "Cat",
    breed: "Sphynx",
    sex: "Female",
    color: "White",
    spayed: "Yes",
    age: "2 Years",
    id: "20872",
    chip: "981120036712394",
    about:
      "Cleo is an elegant Sphynx with a velvety white coat and a playful personality. Despite her hairless appearance, Cleo is incredibly warm and affectionate, always seeking out human contact and cuddles. She enjoys interactive toys, cozy blankets, and lounging in sunny spots. Cleo is great with children and other pets, making her a wonderful addition to any family. She's looking for a forever home where she can be cherished and adored for her unique beauty and loving nature.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Buddy",
    type: "Dog",
    breed: "Bulldog",
    sex: "Male",
    color: "Brindle",
    spayed: "Yes",
    age: "4 Years",
    id: "21583",
    chip: "982000364782369",
    about:
      "Buddy is a charming Bulldog with a distinctive brindle coat and a lovable personality. He has a relaxed and easygoing demeanor, always content to lounge around and soak up the sun. Buddy enjoys leisurely walks, snacking on treats, and cuddling up with his favorite humans. He's great with children and other dogs, making him a delightful companion for a loving family. Buddy is looking for a forever home where he can be pampered and adored for the rest of his days.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Sasha",
    type: "Cat",
    breed: "Himalayan",
    sex: "Female",
    color: "Seal Point",
    spayed: "Yes",
    age: "3 Years",
    id: "22894",
    chip: "981120036712395",
    about:
      "Sasha is a stunning Himalayan cat with a luxurious seal point coat and striking blue eyes. She has a gentle and affectionate demeanor, always eager to curl up in a cozy lap for cuddles. Sasha enjoys quiet evenings, gentle petting sessions, and playing with feather toys. She's great with older children and adults, but she prefers a calm and tranquil environment. Sasha is looking for a loving home where she can be cherished and adored as the regal cat that she is.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Jagger",
    type: "Dog",
    breed: "Boxer",
    sex: "Male",
    color: "Fawn",
    spayed: "Yes",
    age: "3 Years",
    id: "23569",
    chip: "982000364782370",
    about:
      "Jagger is a spirited Boxer with a fawn coat and a zest for life that's contagious. He has a playful and energetic personality, always ready for an adventure or a game of fetch. Rocky enjoys long walks, outdoor activities, and snuggling up with his favorite humans. He's great with children and other dogs, making him a wonderful addition to any family. Rocky is looking for a forever home where he can bring joy and laughter to his new family every day.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Jenna",
    type: "Cat",
    breed: "Maine Coon",
    sex: "Female",
    color: "Calico",
    spayed: "Yes",
    age: "2 Years",
    id: "24375",
    chip: "981120036712396",
    about:
      "Jenna is a delightful Maine Coon with a striking calico coat and a playful personality. She has a curious and adventurous spirit, always eager to explore her surroundings and find new toys to play with. Mittens enjoys interactive playtime, cozy naps in sunny spots, and being showered with affection. She's great with children and other pets, making her a wonderful companion for a loving family. Mittens is looking for a forever home where she can continue to thrive and bring joy to her new family every day.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Duke",
    type: "Dog",
    breed: "Golden Retriever",
    sex: "Male",
    color: "Golden",
    spayed: "Yes",
    age: "4 Years",
    id: "25183",
    chip: "982000364782371",
    about:
      "Duke is a loyal Golden Retriever with a golden coat and a heart of gold. He has a gentle and affectionate demeanor, always eager to please his human companions. Duke enjoys long walks, playing fetch, and lounging in the sun. He's great with children and other pets, making him a wonderful addition to any family. Duke is looking for a forever home where he can be cherished and adored as a beloved member of the family.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
  {
    name: "Princess",
    type: "Cat",
    breed: "Scottish Fold",
    sex: "Female",
    color: "Blue",
    spayed: "Yes",
    age: "2 Years",
    id: "26834",
    chip: "981120036712397",
    about:
      "Princess is a charming Scottish Fold with a soft blue coat and adorable folded ears. She has a sweet and gentle demeanor, always seeking out laps to curl up in. Luna enjoys lounging in cozy spots, playing with feather toys, and watching birds from the window. She's great with children and other pets, making her a delightful companion for a loving family. Luna is looking for a forever home where she can be showered with love and attention.",
    status: [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchipped",
    ],
  },
];
